contentType: Card
UserActions:
  cardId: !!int 18
  hasNotifications: !!bool false
  isIsoloated: !!bool false
  maxItems: !!int 3
  pinnable: !!bool true
title: at-card-recent-files
name: at-card-recent-files
CollectionModeField: null
MaxItemsField: null
PriorityField: null
StreamSource: null
CardComponent: at-card-recent-files/at-card-recent-files-card
StoreMetadataField: null
CommonPart:
  Owner: !!int 2
  Container: null
  CreatedUtc: 2019-04-16T12:52:52.8525738Z
  PublishedUtc: 2019-04-16T12:52:52.8604342Z
  ModifiedUtc: 2019-04-16T12:52:52.8525738Z
  VersionCreatedUtc: 2019-04-16T12:52:52.8525738Z
  VersionPublishedUtc: 2019-04-16T12:52:52.8604342Z
  VersionModifiedUtc: 2019-04-16T12:52:52.8525738Z
ServicePart:
  ConnectorTypeName: ScriptConnector
  ConnectorTypeId: !!int 17
  ConnectorName: Box
  ServiceName: filesandfolders
  Url: ~/api/adenin.GateKeeper.Connector/Box/filesandfolders
  ServiceParameters: '{}'
SearchContextPart:
  Query: null
  Interface: null
CommandPart:
  CommandType: None
  Command: 
  DefaultDate: null
  Intent: null
  Ext: {}
AppPart:
  App: null
  Url: 
  ExtUrl: 
  Priority: !!int 0
  AppFaceId: !!int 0
  Category: orange
  Icon: now:search
  CSSClasses: null
  Enabled: !!bool false
  NewWindow: !!bool false
  UrlWithId: !!bool true
  AvailableAppFaceRecords: null
  HasPattern: !!bool false
RoleViewPermissionsPart:
  AllowedRoles: []
  Audiences:
    - Authenticated
  Mandatory: False
RecurringTaskPart:
  Schedule: '- - - - -'
  ActivityType: adenin.Now.Activities.CardTask.UpdateCard
  StartDateUtc: null
  EndDateUtc: null
  NextOccurrenceUtc: null
  Priority: !!int 5
  Status: Enabled
  NowFlag: 0
  LastExecutionUTC: null
  EnableWebHook: !!bool false
  WebHookToken: null
